# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/sim_debug.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/sim_debug.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15proto/sim_debug.proto\"q\n\x13vehicle_state_debug\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\r\n\x05theta\x18\x05 \x01(\x02\x12\r\n\x05kappa\x18\x06 \x01(\x02\x12\x10\n\x08velocity\x18\x03 \x01(\x02\x12\x14\n\x0c\x61\x63\x63\x65leration\x18\x04 \x01(\x02\"<\n\x10\x63ontroller_debug\x12\x12\n\nkappa_rate\x18\x01 \x01(\x02\x12\x14\n\x0c\x61\x63\x63\x65leration\x18\x02 \x01(\x02\"z\n\tsim_debug\x12\x31\n\x13vehicle_state_debug\x18\x01 \x03(\x0b\x32\x14.vehicle_state_debug\x12+\n\x10\x63ontroller_debug\x18\x02 \x03(\x0b\x32\x11.controller_debug\x12\r\n\x05times\x18\x03 \x03(\x02'
)




_VEHICLE_STATE_DEBUG = _descriptor.Descriptor(
  name='vehicle_state_debug',
  full_name='vehicle_state_debug',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='vehicle_state_debug.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='vehicle_state_debug.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='theta', full_name='vehicle_state_debug.theta', index=2,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='kappa', full_name='vehicle_state_debug.kappa', index=3,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='velocity', full_name='vehicle_state_debug.velocity', index=4,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='acceleration', full_name='vehicle_state_debug.acceleration', index=5,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=138,
)


_CONTROLLER_DEBUG = _descriptor.Descriptor(
  name='controller_debug',
  full_name='controller_debug',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='kappa_rate', full_name='controller_debug.kappa_rate', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='acceleration', full_name='controller_debug.acceleration', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=200,
)


_SIM_DEBUG = _descriptor.Descriptor(
  name='sim_debug',
  full_name='sim_debug',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='vehicle_state_debug', full_name='sim_debug.vehicle_state_debug', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='controller_debug', full_name='sim_debug.controller_debug', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='times', full_name='sim_debug.times', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=324,
)

_SIM_DEBUG.fields_by_name['vehicle_state_debug'].message_type = _VEHICLE_STATE_DEBUG
_SIM_DEBUG.fields_by_name['controller_debug'].message_type = _CONTROLLER_DEBUG
DESCRIPTOR.message_types_by_name['vehicle_state_debug'] = _VEHICLE_STATE_DEBUG
DESCRIPTOR.message_types_by_name['controller_debug'] = _CONTROLLER_DEBUG
DESCRIPTOR.message_types_by_name['sim_debug'] = _SIM_DEBUG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

vehicle_state_debug = _reflection.GeneratedProtocolMessageType('vehicle_state_debug', (_message.Message,), {
  'DESCRIPTOR' : _VEHICLE_STATE_DEBUG,
  '__module__' : 'proto.sim_debug_pb2'
  # @@protoc_insertion_point(class_scope:vehicle_state_debug)
  })
_sym_db.RegisterMessage(vehicle_state_debug)

controller_debug = _reflection.GeneratedProtocolMessageType('controller_debug', (_message.Message,), {
  'DESCRIPTOR' : _CONTROLLER_DEBUG,
  '__module__' : 'proto.sim_debug_pb2'
  # @@protoc_insertion_point(class_scope:controller_debug)
  })
_sym_db.RegisterMessage(controller_debug)

sim_debug = _reflection.GeneratedProtocolMessageType('sim_debug', (_message.Message,), {
  'DESCRIPTOR' : _SIM_DEBUG,
  '__module__' : 'proto.sim_debug_pb2'
  # @@protoc_insertion_point(class_scope:sim_debug)
  })
_sym_db.RegisterMessage(sim_debug)


# @@protoc_insertion_point(module_scope)
